name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Python ${{ matrix.python-version }}, django ${{ matrix.django-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
        django-version: [22, 30, 31, 32, 40, 41, 42]

        exclude:
          - python-version: 2.7
            django-version: 22

          - python-version: 2.7
            django-version: 30

          - python-version: 2.7
            django-version: 31

          - python-version: 2.7
            django-version: 32

          - python-version: 2.7
            django-version: 40

          - python-version: 2.7
            django-version: 41

          - python-version: 2.7
            django-version: 42

          - python-version: 3.10
            django-version: 22

          - python-version: 3.10
            django-version: 30

          - python-version: 3.10
            django-version: 31

          - python-version: 3.11
            django-version: 22

          - python-version: 3.11
            django-version: 30

          - python-version: 3.11
            django-version: 31

          - python-version: 3.11
            django-version: 32

          - python-version: 3.11
            django-version: 40

    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Run Tests
        env:
          TOXENV: django${{ matrix.django-version }}
        run: tox
